# Generated by Django 3.2.7 on 2022-11-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_confirm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='allComment',
        ),
    ]
